### ISSUE TITLE
Hello, I would like to collaborate with your Spanish translator project, which is my native language. could translate the document readme and any other document in order to facilitate the work of Spanish-speaking programmers

### ISSUE THREAD

**Issue by UlisesTJ** [epoberezkin/ajv#714]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript


```

**JSON Schema**

```json


```

**Sample data**

```json


```

**Your code**

```javascript


```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
Thank you.
Please feel free to translate, but it shouldn't be a part of this repository as it won't be possible to keep it in sync. I would suggest to make it clear which version is translated by probably using the same tags in a separate repo.
